CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "People" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "TenantId" text NULL,
    CONSTRAINT "PK_People" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "TenantId" text NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

INSERT INTO "People" ("Id", "Name", "TenantId")
VALUES (1, 'Person 1', 'Teanant 1');
INSERT INTO "People" ("Id", "Name", "TenantId")
VALUES (2, 'Person 2', 'Teanant 2');
INSERT INTO "People" ("Id", "Name", "TenantId")
VALUES (3, 'Person 3', 'Teanant 3');

INSERT INTO "Products" ("Id", "Description", "TenantId")
VALUES (1, 'Description 1', 'Teanant 1');
INSERT INTO "Products" ("Id", "Description", "TenantId")
VALUES (2, 'Description 2', 'Teanant 2');
INSERT INTO "Products" ("Id", "Description", "TenantId")
VALUES (3, 'Description 3', 'Teanant 3');

SELECT setval(
    pg_get_serial_sequence('"People"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "People") + 1,
        nextval(pg_get_serial_sequence('"People"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Products"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Products") + 1,
        nextval(pg_get_serial_sequence('"Products"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211006005359_Tenant01', '5.0.10');

COMMIT;

