CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE dbo."People" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "TenantId" text NULL,
    CONSTRAINT "PK_People" PRIMARY KEY ("Id")
);

CREATE TABLE dbo."Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "TenantId" text NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

INSERT INTO dbo."People" ("Id", "Name", "TenantId")
VALUES (1, 'Person 1', 'Tenant-1');
INSERT INTO dbo."People" ("Id", "Name", "TenantId")
VALUES (2, 'Person 2', 'Tenant-2');
INSERT INTO dbo."People" ("Id", "Name", "TenantId")
VALUES (3, 'Person 3', 'Tenant-3');

INSERT INTO dbo."Products" ("Id", "Description", "TenantId")
VALUES (1, 'Description 1', 'Tenant-1');
INSERT INTO dbo."Products" ("Id", "Description", "TenantId")
VALUES (2, 'Description 2', 'Tenant-2');
INSERT INTO dbo."Products" ("Id", "Description", "TenantId")
VALUES (3, 'Description 3', 'Tenant-3');

SELECT setval(
    pg_get_serial_sequence('dbo."People"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM dbo."People") + 1,
        nextval(pg_get_serial_sequence('dbo."People"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('dbo."Products"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM dbo."Products") + 1,
        nextval(pg_get_serial_sequence('dbo."Products"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211009212713_EstrategiaTenantSchema', '5.0.10');

COMMIT;

